version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/ailinguo
      - PROJECT_NAME=AI Linguo
      - AI_TUTOR_MOCK=1
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ailinguo

volumes:
  mongo_data: